version: '3'
services:
  rpcserver:
    image: rpcserver-rust
    build:
      context: .
      dockerfile: Dockerfile-server
  rpclient:
    image: rpc-client-rust
    build:
      context: .
      dockerfile: Dockerfile-cli
    depends_on:
      - rpcserver